/**
 * Supabase-backed storage for the ATProto OAuth client.
 *
 * `@atproto/oauth-client-node` needs two stores: one for short-lived OAuth
 * "state" during a login round-trip, and one for the long-lived session
 * (access token, refresh token, and the DPoP private key).
 *
 * Everything here uses the SERVICE_ROLE key, which bypasses Row Level Security
 * entirely. That is a deliberate, contained escalation:
 *
 *   - It exists only in this Vercel Function's environment.
 *   - It never reaches a browser, a Worker, or the repo.
 *   - The tables it touches are REVOKEd from anon and have RLS on with no
 *     policies, so even a leak of the anon key reveals nothing here.
 *
 * If you take one habit from this file: service_role is not "the key that
 * works", it is "the key that ignores your safety rails". Use it only in a
 * trusted server context, for data that genuinely must not be public.
 */

import type {
  NodeSavedSession,
  NodeSavedSessionStore,
  NodeSavedState,
  NodeSavedStateStore,
} from "@atproto/oauth-client-node";

function serviceConfig() {
  const url = process.env.SUPABASE_URL?.trim().replace(/\/+$/, "");
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();

  if (!url || !key) {
    throw new Error(
      "ATProto OAuth needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY. " +
        "The service_role key is secret — set it with `vercel env add`, never in git.",
    );
  }

  return {
    url,
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
    },
  };
}

async function upsert(table: string, row: Record<string, unknown>): Promise<void> {
  const { url, headers } = serviceConfig();

  const response = await fetch(`${url}/rest/v1/${table}`, {
    method: "POST",
    // merge-duplicates makes this an UPSERT keyed on the primary key, which is
    // what the OAuth client expects `set()` to mean.
    headers: { ...headers, Prefer: "resolution=merge-duplicates" },
    body: JSON.stringify(row),
  });

  if (!response.ok) {
    throw new Error(`Failed to write ${table}: ${response.status} ${await response.text()}`);
  }
}

/**
 * NOTE on the filter below, because the shape is what gets copy-pasted.
 *
 * `${column}=eq.${encodeURIComponent(value)}` builds a PostgREST filter by
 * string concatenation. It is safe HERE for two specific reasons — the values
 * are a JWT-verified DID and a key generated by the OAuth library, and
 * encodeURIComponent escapes `&` and `=` so a value cannot introduce a new
 * query parameter — but neither reason is visible at the call site, and
 * encodeURIComponent does NOT escape `.`, `!`, `~`, `*`, `'`, `(` or `)`.
 *
 * If you reuse this with a value a user controls, use a PostgREST client or
 * validate the input first. Do not assume the escaping saves you.
 */
async function selectOne<T>(table: string, column: string, value: string): Promise<T | null> {
  const { url, headers } = serviceConfig();

  const response = await fetch(
    `${url}/rest/v1/${table}?${column}=eq.${encodeURIComponent(value)}&limit=1`,
    { headers },
  );

  if (!response.ok) {
    throw new Error(`Failed to read ${table}: ${response.status}`);
  }

  const rows = (await response.json()) as T[];
  return rows[0] ?? null;
}

async function remove(table: string, column: string, value: string): Promise<void> {
  const { url, headers } = serviceConfig();
  await fetch(`${url}/rest/v1/${table}?${column}=eq.${encodeURIComponent(value)}`, {
    method: "DELETE",
    headers,
  });
}

/**
 * Sweep abandoned OAuth states.
 *
 * The callback deletes the state it consumed, but a login nobody finishes
 * leaves its row behind, and /api/atproto/login is unauthenticated — so anyone
 * can create those rows as fast as they can send requests.
 *
 * `expire_atproto_states()` is also on a pg_cron schedule (see
 * supabase/migrations/…_expire_oauth_states.sql). Calling it here too means
 * cleanup still happens if pg_cron is unavailable on the plan, and neither
 * mechanism is load-bearing alone.
 *
 * Deliberately fire-and-forget: this is housekeeping, and a visitor's login
 * must never fail or slow down because the sweep had a bad day.
 */
export async function sweepExpiredStates(): Promise<void> {
  try {
    const { url, headers } = serviceConfig();
    await fetch(`${url}/rest/v1/rpc/expire_atproto_states`, { method: "POST", headers });
  } catch {
    // Housekeeping only. Never surface this to the caller.
  }
}

/**
 * OAuth state: created when a login starts, consumed at the callback.
 * Single-use by design — `del` is called as soon as it has served its purpose,
 * which is what stops a captured state from being replayed.
 */
export const stateStore: NodeSavedStateStore = {
  async set(key: string, state: NodeSavedState) {
    await upsert("atproto_states", { key, state });
  },

  async get(key: string) {
    const row = await selectOne<{ state: NodeSavedState }>("atproto_states", "key", key);
    return row?.state ?? undefined;
  },

  async del(key: string) {
    await remove("atproto_states", "key", key);
  },
};

/**
 * The long-lived session, keyed by DID.
 *
 * The library refreshes tokens on its own and calls set() again with the new
 * values, so this must genuinely persist — an in-memory store would silently
 * log everyone out on each cold start.
 */
export const sessionStore: NodeSavedSessionStore = {
  async set(did: string, session: NodeSavedSession) {
    await upsert("atproto_sessions", {
      did,
      // Denormalised purely so ops queries can read a handle without decoding
      // the session blob. Never trusted as identity — the DID is the identity.
      handle: (session as { tokenSet?: { sub?: string } }).tokenSet?.sub ?? did,
      session,
      updated_at: new Date().toISOString(),
    });
  },

  async get(did: string) {
    const row = await selectOne<{ session: NodeSavedSession }>(
      "atproto_sessions",
      "did",
      did,
    );
    return row?.session ?? undefined;
  },

  async del(did: string) {
    await remove("atproto_sessions", "did", did);
  },
};
